=== ckw20/NetAutoTest_Hackathon/data/testcases/examples/one-tester-one-dut/cfg_template_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Testcase Schema",
    "type": "object",
    "properties": {
      "type": {
        "type": "string",
        "enum": ["Testcase"]
      },
      "name": {
        "type": "string"
      },
      "tc_no": {
        "type": "string"
      },
      "version": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "default": {
            "type": "string"
          }
        },
        "required": ["default"]
      },
      "arg": {
        "type": "object"
      },
      "dut": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "dut_cfg": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "port": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": ["type", "name", "tc_no", "version", "arg", "dut", "dut_cfg", "port"]
  }

=== ckw20/NetAutoTest_Hackathon/data/ref_projects/cepri-dev-new/Testcase/tc_6_7_3/cfg.json
{
 "type":"Testcase",
 "name":"Dynamic Host Configuration Protocol (DHCP)",
 "tc_no":"tc_6_7_3",
 "version": {
  "description": "Version number, use development or modification date",
  "default": "v20240917"
 },
 "arg":{
  "interface": {
   "description": "Tester port MAC address setting",
   "default": {
     "ipv4_up_address":{
      "description": "Uplink port IPv4 address setting",
      "default": "192.168.1.100"
     },
     "ipv4_up_gateway":{
      "description": "Uplink port IPv4 gateway setting",
      "default": "192.168.1.1"
     }
   }
  }
 },
 "dut":["DeviceA"],
 "dut_cfg":["DeviceA_Setup","DeviceA_Teardown"],
 "port":["PortDeviceA_1","PortDeviceA_2"]
}

=== ckw20/NetAutoTest_Hackathon/example_results/configure_generation_examples/tc_6_7_4/cfg.json
{
 "type":"Testcase",
 "name":"Static Routing",
 "tc_no":"tc_6_7_4",
 "version": {
  "description": "Version number, use development or modification date",
  "default": "v20240917"
 },
 "arg":{
  "interface": {
   "description": "Tester port MAC address setting",
   "default": {
     "mac_up_address": {
      "description": "Uplink port MAC address setting",
      "default": "00:01:02:02:02:02"
     },
     "mac_down_address":{
      "description": "Downlink port MAC address setting",
      "default": "00:01:02:02:02:02"
     },
     "ipv4_up_address":{
      "description": "Uplink port IPv4 address setting",
      "default": "192.168.1.100"
     },
     "ipv4_up_gateway":{
      "description": "Uplink port IPv4 gateway setting",
      "default": "192.168.1.1"
     },
     "ipv4_down_address":{
      "description": "Downlink port IPv4 address setting",
      "default": "192.168.2.100"
     },
     "ipv4_down_gateway":{
      "description": "Downlink port IPv4 gateway setting",
      "default": "192.168.2.1"
     }
   }
  }
 },
 "dut":["DeviceA","DeviceB"],
 "dut_cfg":["DeviceA_Setup","DeviceA_Teardown","DeviceB_Setup","DeviceB_Teardown"],
 "port":["PortDeviceA_1","PortDeviceA_2","PortDeviceB_1","PortDeviceB_2"]
}

=== ckw20/NetAutoTest_Hackathon/data/testcases/exp_res/from_examples/tc643_mdf/cfg.json
{
 "type":"Testcase",
 "name":"端口吞吐量",
 "tc_no":"tc643",
 "version": {
  "description": "版本号，使用开发或修改日期",
  "default": "v20240902"
 },
 "arg":{
  "interface": {
   "description": "仪表接口Mac地址设置",
   "default": {
     "up": {
      "description": "上行接口Mac地址设置",
      "default": "00:01:01:02:02:02"
     },
     "down":{
      "description": "下行接口Mac地址设置",
      "default": "00:01:02:02:02:02"
     }
   }
  },
  "frame_size":{
   "description":"测试帧长",
   "default": [64, 1024, 9000]
  },
  "duration": {
   "description": "每个帧长测试时长",
   "default": 10
  },
  "search": {
   "description": "二分法测试设置",
   "default": {
     "init": {
      "description": "初始负载",
      "default": 100
     },
     "lower": {
      "description": "最小负载",
      "default": 100
     },
     "upper": {
      "description": "最大负载",
      "default": 100
     }
   }
  }
 },
 "dut":["DeviceA"],
 "dut_cfg":["DeviceA_Setup","DeviceA_Teardown"],
 "port":["PortDeviceA_1","PortDeviceA_2"]
}

=== ckw20/NetAutoTest_Hackathon/example_results/configure_generation_examples/tc_6_5_9/cfg.json
{
 "type":"Testcase",
 "name":"生成树协议",
 "tc_no":"tc_6_5_9",
 "version": {
  "description": "版本号，使用开发或修改日期",
  "default": "v20240917"
 },
 "arg":{
  "interface": {
   "description": "仪表接口Mac地址设置",
   "default": {
     "up": {
      "description": "上行接口Mac地址设置",
      "default": "00:01:01:02:02:02"
     },
     "down":{
      "description": "下行接口Mac地址设置",
      "default": "00:01:02:02:02:02"
     }
   }
  }
 },
 "dut":["DeviceA","DeviceB","DeviceC","DeviceD"],
 "dut_cfg":["DeviceA_Setup","DeviceA_Teardown","DeviceB_Setup","DeviceB_Teardown","DeviceC_Setup","DeviceC_Teardown","DeviceD_Setup","DeviceD_Teardown"],
 "port":["PortDeviceA_1","PortDeviceA_2"]
}

=== ckw20/NetAutoTest_Hackathon/example_results/configure_generation_examples/tc_6_4_7/cfg.json
{
 "type": "Testcase",
 "name": "Address Learning Rate",
 "tc_no": "tc_6_4_7",
 "version": {
  "description": "Version number, use development or modification date",
  "default": "v20240917"
 },
 "arg": {
  "interface": {
   "description": "Interface MAC address setting",
   "default": {
    "up": {
     "description": "Uplink interface MAC address setting",
     "default": "00:01:01:02:02:02"
    },
    "down": {
     "description": "Downlink interface MAC address setting",
     "default": "00:01:02:02:02:02"
    }
   }
  },
  "frame_size": {
   "description": "Test frame size",
   "default": [64]
  },
  "learning_capacity": {
   "description": "Configure the number of learning addresses and the address learning rate",
   "default": {
    "min_rate_count": {
     "description": "Minimum address learning rate",
     "default": 1000
    },
    "max_rate_count": {
     "description": "Maximum address learning rate",
     "default": 5000
    },
    "init_rate_count": {
     "description": "Initial address learning rate",
     "default": 5000
    },
    "resolution": {
     "description": "Error",
     "default": 2
    },
    "aging_time": {
     "description": "Aging time",
     "default": 30
    },
    "address_count": {
     "description": "Number of addresses",
     "default": 16000
    }
   }
  }
 },
 "dut": ["DeviceA"],
 "dut_cfg": ["DeviceA_Setup", "DeviceA_Teardown"],
 "port": ["PortDeviceA_1", "PortDeviceA_2", "PortDeviceA_3"]
}

=== ckw20/NetAutoTest_Hackathon/example_results/configure_generation_examples/tc_6_4_6/cfg.json
{
 "type": "Testcase",
 "name": "Address Cache Capacity",
 "tc_no": "tc_6_4_6",
 "version": {
  "description": "Version number, use development or modification date",
  "default": "v20240917"
 },
 "arg": {
  "interface": {
   "description": "Interface MAC address setting",
   "default": {
    "up": {
     "description": "Uplink interface MAC address setting",
     "default": "00:01:01:02:02:02"
    },
    "down": {
     "description": "Downlink interface MAC address setting",
     "default": "00:01:02:02:02:02"
    }
   }
  },
  "frame_size": {
   "description": "Test frame size",
   "default": [64]
  },
  "learning_capacity": {
   "description": "Configure the number of learning addresses and the address learning rate",
   "default": {
    "min_address_count": {
     "description": "Minimum number of addresses",
     "default": 5000
    },
    "max_address_count": {
     "description": "Maximum number of addresses",
     "default": 16000
    },
    "init_address_count": {
     "description": "Initial number of addresses",
     "default": 16000
    },
    "resolution": {
     "description": "Error",
     "default": 2
    },
    "aging_time": {
     "description": "Aging time",
     "default": 30
    },
    "learning_rate": {
     "description": "Learning rate",
     "default": 1000
    }
   }
  }
 },
 "dut": ["DeviceA"],
 "dut_cfg": ["DeviceA_Setup", "DeviceA_Teardown"],
 "port": ["PortDeviceA_1", "PortDeviceA_2", "PortDeviceA_3"]
}

=== ckw20/NetAutoTest_Hackathon/example_results/configure_generation_examples/tc_6_5_1/cfg.json
{
 "type":"Testcase",
 "name":"Virtual LAN (VLAN) Function",
 "tc_no":"tc_6_5_1",
 "version": {
  "description": "Version number, use development or modification date",
  "default": "v20240918"
 },
 "arg":{
  "interface": {
   "description": "Tester port MAC address setting",
   "default": {
     "mac_up_address": {
      "description": "Uplink port MAC address setting",
      "default": "00:01:02:02:02:02"
     },
     "mac_down_address":{
      "description": "Downlink port MAC address setting",
      "default": "00:01:02:02:02:02"
     },
     "ipv4_up_address":{
      "description": "Uplink port IPv4 address setting",
      "default": "192.168.1.100"
     },
     "ipv4_up_gateway":{
      "description": "Uplink port IPv4 gateway setting",
      "default": "192.168.1.1"
     },
     "ipv4_down_address":{
      "description": "Downlink port IPv4 address setting",
      "default": "192.168.2.100"
     },
     "ipv4_down_gateway":{
      "description": "Downlink port IPv4 gateway setting",
      "default": "192.168.2.1"
     }
   }
  },
  "load_profile": {
   "description": "Port load setting",
   "default": {
      "rate": {
        "description": "Traffic sending port rate, unit: %",
        "default": 100
     },
     "seconds": {
       "description": "Traffic sending duration, unit: seconds",
       "default": 30
     }
   }
  }
 },
 "dut":["DeviceA"],
 "dut_cfg":["DeviceA_Setup","DeviceA_Teardown"],
 "port":["PortDeviceA_1","PortDeviceA_2", "PortDeviceA_3"]
}

=== ckw20/NetAutoTest_Hackathon/example_results/configure_generation_examples/tc_6_5_6/cfg.json
{
 "type":"Testcase",
 "name":"IGMP-Snooping 组播",
 "tc_no":"tc_6_5_6",
 "version": {
  "description": "版本号，使用开发或修改日期",
  "default": "v20240918"
 },
 "arg":{
  "interface": {
   "description": "仪表接口Mac地址设置",
   "default": {
     "mac_up_address": {
      "description": "上行接口Mac地址设置",
      "default": "00:01:02:02:02:02"
     },
     "mac_down_address":{
      "description": "下行接口Mac地址设置",
      "default": "00:01:02:02:02:02"
     },
     "ipv4_up_address":{
      "description": "上行接口IPv4地址设置",
      "default": "192.168.1.100"
     },
     "ipv4_up_gateway":{
      "description": "上行接口IPv4网关设置",
      "default": "192.168.1.1"
     },
     "ipv4_down_address":{
      "description": "下行接口IPv4地址设置",
      "default": "192.168.2.100"
     },
     "ipv4_down_gateway":{
      "description": "下行接口IPv4网关设置",
      "default": "192.168.2.1"
     }
   }
  },
  "load_profile": {
   "description": "端口负载设置",
   "default": {
      "rate": {
        "description": "流量发送端口速率，单位：%",
        "default": 100
     },
     "seconds": {
       "description": "流量发送时长，单位：秒",
       "default": 100
     }
   }
  }
 },
 "dut":["DeviceA"],
 "dut_cfg":["DeviceA_Setup","DeviceA_Step3","DeviceA_Teardown"],
 "port":["PortDeviceA_1","PortDeviceA_2"]
}
