=== ckw20/NetAutoTest_Hackathon/data/testcases/examples/one-tester-one-dut/cfg_template_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Testcase Schema",
    "type": "object",
    "properties": {
      "type": {
        "type": "string",
        "enum": ["Testcase"]
      },
      "name": {
        "type": "string"
      },
      "tc_no": {
        "type": "string"
      },
      "version": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "default": {
            "type": "string"
          }
        },
        "required": ["default"]
      },
      "arg": {
        "type": "object"
      },
      "dut": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "dut_cfg": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "port": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": ["type", "name", "tc_no", "version", "arg", "dut", "dut_cfg", "port"]
  }

=== ckw20/NetAutoTest_Hackathon/data/ref_projects/cepri-dev-new/Testcase/tc_6_4_4/cfg.json
{
 "type": "Testcase",
 "name": "Store-and-Forward Latency",
 "tc_no": "tc_6_4_4",
 "version": {
  "description": "Version number, use development or modification date",
  "default": "v20240916"
 },
 "arg": {
  "interface": {
   "description": "Interface MAC address setting",
   "default": {
    "up": {
     "description": "Uplink interface MAC address setting",
     "default": "00:01:01:02:02:02"
    },
    "down": {
     "description": "Downlink interface MAC address setting",
     "default": "00:01:02:02:02:02"
    }
   }
  },
  "frame_size": {
   "description": "Test frame size",
   "default": [64, 65, 256, 1024, 1518]
  },
  "duration": {
   "description": "Test duration for each frame size",
   "default": 60
  },
  "traffic_load_loop": {
   "description": "Binary search test setting",
   "default": {
    "load_unit": {
     "description": "Unit",
     "default": "percent"
    },
    "load_custom": {
     "description": "Custom load",
     "default": [10, 95]
    }
   }
  }
 },
 "dut": ["DeviceA"],
 "dut_cfg": ["DeviceA_Setup", "DeviceA_Teardown"],
 "port": ["PortDeviceA_1", "PortDeviceA_2"]
}

=== ckw20/NetAutoTest_Hackathon/example_results/configure_generation_examples/tc_6_4_3/cfg.json
{
 "type": "Testcase",
 "name": "Port Throughput",
 "tc_no": "tc_6_4_3",
 "version": {
  "description": "Version number, use development or modification date",
  "default": "v20240902"
 },
 "arg": {
  "interface": {
   "description": "Interface MAC address setting",
   "default": {
    "up": {
     "description": "Uplink interface MAC address setting",
     "default": "00:01:01:02:02:02"
    },
    "down": {
     "description": "Downlink interface MAC address setting",
     "default": "00:01:02:02:02:02"
    }
   }
  },
  "frame_size": {
   "description": "Test frame size",
   "default": [64, 65, 256, 1024, 1518, 9000]
  },
  "duration": {
   "description": "Test duration for each frame size",
   "default": 60
  },
  "search": {
   "description": "Binary search test setting",
   "default": {
    "init": {
     "description": "Initial load",
     "default": 100
    },
    "lower": {
     "description": "Minimum load",
     "default": 100
    },
    "upper": {
     "description": "Maximum load",
     "default": 100
    }
   }
  }
 },
 "dut": ["DeviceA"],
 "dut_cfg": ["DeviceA_Setup", "DeviceA_Teardown"],
 "port": ["PortDeviceA_1", "PortDeviceA_2"]
}

=== ckw20/NetAutoTest_Hackathon/example_results/configure_generation_examples/tc_6_6_1/cfg.json
{
 "type": "Testcase",
 "name": "Layer 3 Forwarding Rate",
 "tc_no": "tc_6_6_1",
 "version": {
  "description": "Version number, use development or modification date",
  "default": "v20240917"
 },
 "arg": {
  "interface": {
   "description": "Interface MAC address setting",
   "default": {
    "mac_up_address": {
     "description": "Uplink interface MAC address setting",
     "default": "00:01:02:02:02:02"
    },
    "mac_down_address": {
     "description": "Downlink interface MAC address setting",
     "default": "00:01:02:02:02:02"
    },
    "ipv4_up_address": {
     "description": "Uplink interface IPv4 address setting",
     "default": "192.168.1.100"
    },
    "ipv4_up_gateway": {
     "description": "Uplink interface IPv4 gateway setting",
     "default": "192.168.1.1"
    },
    "ipv4_down_address": {
     "description": "Downlink interface IPv4 address setting",
     "default": "192.168.2.100"
    },
    "ipv4_down_gateway": {
     "description": "Downlink interface IPv4 gateway setting",
     "default": "192.168.2.1"
    }
   }
  },
  "load_profile": {
   "description": "Port load setting",
   "default": {
    "rate": {
     "description": "Traffic sending port rate, unit: %",
     "default": 100
    },
    "seconds": {
     "description": "Traffic sending duration, unit: seconds",
     "default": 100
    }
   }
  },
  "stream": {
   "description": "Traffic setting",
   "default": {
    "frame_size": {
     "description": "Traffic sending frame size",
     "default": [64, 128, 256, 512, 1024, 1518]
    }
   }
  }
 },
 "dut": ["DeviceA"],
 "dut_cfg": ["DeviceA_Setup", "DeviceA_Teardown"],
 "port": ["PortDeviceA_1", "PortDeviceA_2"]
}

=== ckw20/NetAutoTest_Hackathon/data/ref_projects/cepri-dev-new/Testcase/tc_6_5_3/cfg.json
{
 "type":"Testcase",
 "name":"Head-of-Line Blocking Test",
 "tc_no":"tc_6_5_3",
 "version": {
  "description": "Version number, use development or modification date",
  "default": "v20240918"
 },
 "arg":{
  "interface": {
   "description": "Tester port MAC address setting",
   "default": {
     "mac_up_address": {
      "description": "Uplink port MAC address setting",
      "default": "00:01:02:02:02:02"
     },
     "mac_down_address":{
      "description": "Downlink port MAC address setting",
      "default": "00:01:02:02:02:02"
     },
     "ipv4_up_address":{
      "description": "Uplink port IPv4 address setting",
      "default": "192.168.1.100"
     },
     "ipv4_up_gateway":{
      "description": "Uplink port IPv4 gateway setting",
      "default": "192.168.1.1"
     },
     "ipv4_down_address":{
      "description": "Downlink port IPv4 address setting",
      "default": "192.168.2.100"
     },
     "ipv4_down_gateway":{
      "description": "Downlink port IPv4 gateway setting",
      "default": "192.168.2.1"
     }
   }
  },
  "load_profile": {
   "description": "Port load setting",
   "default": {
      "rate": {
        "description": "Traffic sending port rate, unit: %",
        "default": 100
     },
     "seconds": {
       "description": "Traffic sending duration, unit: seconds",
       "default": 100
     }
   }
  },
   "ospf": {
   "description": "OSPF protocol setting",
   "default": {
      "priority_session_up": {
        "description": "Uplink port protocol priority",
        "default": 1
     },
      "priority_session_down": {
        "description": "Downlink port protocol priority",
        "default": 1
     },
     "area_id": {
        "description": "Area ID",
        "default": "0.0.0.0"
     },
     "advertise_count": {
        "description": "Total number of advertised routes",
        "default": 1000
     },
     "advertise_wait": {
        "description": "Wait time after advertising routes, unit: seconds",
        "default": 30
     }
   }
  }
 },
 "dut":["DeviceA"],
 "dut_cfg":["DeviceA_Setup","DeviceA_Teardown"],
 "port":["PortDeviceA_1","PortDeviceA_2", "PortDeviceA_3", "PortDeviceA_4"]
}

=== ckw20/NetAutoTest_Hackathon/data/testcases/seeds/industry/cepri/tc_6_7_5/cfg.json
{
 "type":"Testcase",
 "name":"路由信息协议（RIP",
 "tc_no":"tc_6_7_5",
 "version": {
  "description": "版本号，使用开发或修改日期",
  "default": "v20240917"
 },
 "arg":{
  "interface": {
   "description": "仪表接口Mac地址设置",
   "default": {
     "mac_up_address": {
      "description": "上行接口Mac地址设置",
      "default": "00:01:01:02:02:02"
     },
     "mac_down_address":{
      "description": "下行接口Mac地址设置",
      "default": "00:01:02:02:02:02"
     },
     "ipv4_up_address":{
      "description": "上行接口IPv4地址设置",
      "default": "192.168.1.100"
     },
     "ipv4_up_gateway":{
      "description": "上行接口IPv4网关设置",
      "default": "192.168.1.1"
     },
     "ipv4_down_address":{
      "description": "下行接口IPv4地址设置",
      "default": "192.168.2.100"
     },
     "ipv4_down_gateway":{
      "description": "下行接口IPv4网关设置",
      "default": "192.168.2.1"
     }
   }
  }
 },
 "dut":["DeviceA"],
 "dut_cfg":["DeviceA_Setup","DeviceA_Teardown"],
 "port":["PortDeviceA_1","PortDeviceA_2"]
}

=== ckw20/NetAutoTest_Hackathon/data/ref_projects/cepri-dev-new/Testcase/tc_6_5_5/cfg.json
{
 "type":"Testcase",
 "name":"多链路聚合",
 "tc_no":"tc_6_5_5",
 "version": {
  "description": "版本号，使用开发或修改日期",
  "default": "v20240918"
 },
 "arg":{
  "interface": {
   "description": "仪表接口Mac地址设置",
   "default": {
     "mac_up_address": {
      "description": "上行接口Mac地址设置",
      "default": "00:01:02:02:02:02"
     },
     "mac_down_address":{
      "description": "下行接口Mac地址设置",
      "default": "00:01:02:02:02:02"
     },
     "ipv4_up_address":{
      "description": "上行接口IPv4地址设置",
      "default": "192.168.1.100"
     },
     "ipv4_up_gateway":{
      "description": "上行接口IPv4网关设置",
      "default": "192.168.1.1"
     },
     "ipv4_down_address":{
      "description": "下行接口IPv4地址设置",
      "default": "192.168.2.100"
     },
     "ipv4_down_gateway":{
      "description": "下行接口IPv4网关设置",
      "default": "192.168.2.1"
     }
   }
  },
  "load_profile": {
   "description": "端口负载设置",
   "default": {
      "rate": {
        "description": "流量发送端口速率，单位：%",
        "default": 100
     },
     "seconds": {
       "description": "流量发送时长，单位：秒",
       "default": 100
     }
   }
  },
   "ospf": {
   "description": "OSPF协议设置",
   "default": {
      "priority_session_up": {
        "description": "上行端口协议优先级",
        "default": 1
     },
      "priority_session_down": {
        "description": "下行端口协议优先级",
        "default": 1
     },
     "area_id": {
        "description": "区域ID",
        "default": "0.0.0.0"
     },
     "advertise_count": {
        "description": "通告路由总数",
        "default": 1000
     },
     "advertise_wait": {
        "description": "通告路由后等待时长，单位：秒",
        "default": 30
     }
   }
  }
 },
 "dut":["DeviceA"],
 "dut_cfg":["DeviceA_Setup","DeviceA_Teardown"],
 "port":["PortDeviceA_1","PortDeviceA_2", "PortDeviceA_3", "PortDeviceA_4"]
}

=== ckw20/NetAutoTest_Hackathon/data/testcases/seeds/industry/cepri/tc_6_7_3/cfg.json
{
 "type":"Testcase",
 "name":"动态主机配置协议（DHCP)",
 "tc_no":"tc_6_7_3",
 "version": {
  "description": "版本号，使用开发或修改日期",
  "default": "v20240917"
 },
 "arg":{
  "interface": {
   "description": "仪表接口Mac地址设置",
   "default": {
     "ipv4_up_address":{
      "description": "上行接口IPv4地址设置",
      "default": "192.168.1.100"
     },
     "ipv4_up_gateway":{
      "description": "上行接口IPv4网关设置",
      "default": "192.168.1.1"
     }
   }
  }
 },
 "dut":["DeviceA"],
 "dut_cfg":["DeviceA_Setup","DeviceA_Teardown"],
 "port":["PortDeviceA_1","PortDeviceA_2"]
}

=== ckw20/NetAutoTest_Hackathon/data/ref_projects/cepri-dev-new/Testcase/tc_6_7_5/cfg.json
{
 "type": "Testcase",
 "name": "Routing Information Protocol (RIP)",
 "tc_no": "tc_6_7_5",
 "version": {
  "description": "Version number, use development or modification date",
  "default": "v20240917"
 },
 "arg": {
  "interface": {
   "description": "Interface MAC address setting",
   "default": {
    "mac_up_address": {
     "description": "Uplink interface MAC address setting",
     "default": "00:01:01:02:02:02"
    },
    "mac_down_address": {
     "description": "Downlink interface MAC address setting",
     "default": "00:01:02:02:02:02"
    },
    "ipv4_up_address": {
     "description": "Uplink interface IPv4 address setting",
     "default": "192.168.1.100"
    },
    "ipv4_up_gateway": {
     "description": "Uplink interface IPv4 gateway setting",
     "default": "192.168.1.1"
    },
    "ipv4_down_address": {
     "description": "Downlink interface IPv4 address setting",
     "default": "192.168.2.100"
    },
    "ipv4_down_gateway": {
     "description": "Downlink interface IPv4 gateway setting",
     "default": "192.168.2.1"
    }
   }
  }
 },
 "dut": ["DeviceA"],
 "dut_cfg": ["DeviceA_Setup", "DeviceA_Teardown"],
 "port": ["PortDeviceA_1", "PortDeviceA_2"]
}
